---
- name: Discourse | create folder
  file: path={{ discourse.root_path }} state=directory owner={{ discourse.user }}
  register: folder

- name: Discourse | clone from GitHub repo
  git: repo=https://github.com/discourse/discourse_docker.git dest={{ discourse.root_path }}
  when: folder|changed

- name: Discourse | setup conf
  template: src={{ discourse.app_conf }} dest={{ discourse.root_path }}/containers/app.yml owner={{ discourse.user }} force=yes

- name: Discourse | installation
  shell: echo | /bin/bash launcher bootstrap app chdir={{ discourse.root_path }}
  when: folder|changed

- name: Discourse | start application
  shell: /bin/bash launcher start app chdir={{ discourse.root_path }}
