---
- name: Discourse | create folder
  file: path={{ discourse_app.root_path }} state=directory owner={{ discourse_app.user }}
  register: folder

- name: Discourse | clone from GitHub repo
  git: repo=https://github.com/discourse/discourse_docker.git
  clone: yes
  dest: {{ discourse_app.root_path }}
  when: folder|changed

- name: Discourse | copy configuration file
  template: src=templates/app.yml.j2 dest={{ discourse_app.root_path }}/containers/app.yml owner={{ discourse_app.user }}
  when: folder|changed

- name: Discourse | installation
  command: ./launcher bootstrap app chdir={{ discourse_app.root_path }}
  user: {{ discourse_app.user }}
  when: folder|changed

- name: Discourse | start application
  command: ./launcher start app chdir={{ discourse_app.root_path }}
  user: {{ discourse_app.user }}
